### ISSUE TITLE
connection of rtl-sdr to gr-iridium

### ISSUE THREAD

**Issue by michael040101** [muccc/gr-iridium#123]
Hi,
My system is ubuntu 20.04 and gnuradio3.9.
Im trying to run the program and get the followig output,

michael@ubuntu:~/Desktop/gr-iridium-maint-3.9$ sudo iridium-extractor -D 4 examples/rtl-sdr.conf > output.bits
[sudo] password for michael: 
gr-osmosdr 0.2.0.0 (0.2.0) gnuradio 3.9.5.0
built-in source types: file rtl_tcp rfspace redpitaya 
Traceback (most recent call last):
  File "/usr/local/bin/iridium-extractor", line 356, in <module>
    tb = iridium.iridium_extractor_flowgraph.FlowGraph(center_frequency=center, sample_rate=sample_rate, decimation=decimation, 
  File "/usr/local/lib/python3.8/dist-packages/iridium/iridium_extractor_flowgraph.py", line 130, in __init__
    source = osmosdr.source()
RuntimeError: No supported devices found (check the connection and/or udev rules).

I assume its because the RTL-SDR is not recognized by gr-iridium.
I tried to install gr-osmosdr but it didnt help.
The RTL-SDR is recognized by other tools, like CubicSDR.

How can I solve this issue?

Thanks!

**Comment by dg9bja** [comment]
Please look at built-in source types
Here is a sample of mine: gr-osmosdr 0.2.0.0 (0.2.0) gnuradio 3.8.1.0
built-in source types: file osmosdr fcd rtl rtl_tcp uhd miri hackrf bladerf rfspace airspy airspyhf soapy redpitaya freesrp
That's a point you can look at
