### ISSUE TITLE
Error: Iridium Sniffer Setup Issue with gr-iridium and HackRF on Ubuntu 22.04

### ISSUE THREAD

**Issue by ashwini1890** [muccc/gr-iridium#198]
I'm new to gr-iridium and the Iridium Toolkit, attempting to build my own Iridium sniffer using Ubuntu 22.04 and HackRF. Following recommendations, I've installed GNU Radio 3.10. When I ran the command sudo iridium-extractor -D 4 examples/hackrf.conf > output.bits to sniff packets, I encountered an error. Could someone please explain the reason for this error and help me resolve it?

HP-ZBook-15:~/gr-iridium$ sudo iridium-extractor -D 4 examples/hackrf.conf > output.bits
Traceback (most recent call last):
  File "/usr/local/bin/iridium-extractor", line 357, in <module>
    tb = iridium.iridium_extractor_flowgraph.FlowGraph(center_frequency=center, sample_rate=sample_rate, decimation=decimation, 
  File "/usr/local/lib/python3.10/dist-packages/iridium/iridium_extractor_flowgraph.py", line 150, in __init__
    source = osmosdr.source(args=d['device_args'])
RuntimeError: logger_set_level: Bad level type.
corrupted size vs. prev_size in fastbins
Aborted

![Screenshot from 2024-07-25 18-25-40](https://github.com/user-attachments/assets/72b1e99b-565a-4d5a-a44f-7fa459b69747)

**Comment by schneider42** [comment]
Is it possible that you have multiple versions of gr-iridium installed? can you delete the whole `/usr/local/lib/python3.10/dist-packages/iridium` folder and try again?

**Comment by ashwini1890** [comment]
no i have only 1 version of gr-iridium. if i will delete this the iridium module will be deleted 
![Screenshot from 2024-07-30 12-12-15](https://github.com/user-attachments/assets/c4d18943-5a63-47a3-90ed-218a8c312c63)
