### ISSUE TITLE
iridium-extractor  No module named filter but gr-filter is installed

### ISSUE THREAD

**Issue by gch230** [muccc/gr-iridium#35]
Running gnuradio 3.7.11.1 from ubuntu with all libs installed and dependencies.  gr-iridium compiles, installs, then when run throws the below error message.

Traceback (most recent call last):
  File "/usr/local/bin/iridium-extractor", line 10, in <module>
    import iridium.iridium_extractor_flowgraph
  File "/usr/local/lib/python2.7/dist-packages/iridium/iridium_extractor_flowgraph.py", line 9, in <module>
    import gnuradio.filter
ImportError: No module named filter

**Comment by schneider42** [comment]
3.7 is considered legacy by now. Please give newer versions a try.
