### ISSUE TITLE
FFT_burst error

### ISSUE THREAD

**Issue by dsound** [muccc/gr-iridium#4]
Getting this error when I run ` iridium-extractor -D 4 hackrf.conf | grep "A:OK" > output.bits` in the 'examples' folder:

`gr-osmosdr 0.1.4 (0.1.4) gnuradio 3.7.9
built-in source types: file osmosdr fcd rtl rtl_tcp uhd miri hackrf bladerf rfspace airspy redpitaya 
Using HackRF One with firmware 2014.08.1 
(RF) Gain: 14.0 (Requested 20)
IF Gain: 40.0 (Requested 40)
BB Gain: 20.0 (Requested 20)
Bandwidth: 10000000.0 (Requested 10000000)
Traceback (most recent call last):
  File "/usr/local/bin/iridium-extractor", line 193, in <module>
    verbose=verbose)
  File "/usr/local/lib/python2.7/dist-packages/iridium/iridium_extractor_flowgraph.py", line 175, in __init__
    self._fft_burst_tagger = iridium.fft_burst_tagger(center_frequency=self._center_frequency,
AttributeError: 'module' object has no attribute 'fft_burst_tagger'
`

I'm using Ubuntu 16.04 LTS

**Comment by dsound** [comment]
It turns out the above error is just a bad install of Gnuradio. Make sure to install via build-script.
